apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-tarefas-familia-ingress
  namespace: api-tarefas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ""
      http:
        paths:
          - path: /apitarefasfamilia(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-tarefas-familia
                port:
                  number: 8000
